### ISSUE TITLE
vs. net/html parser

### ISSUE THREAD

**Issue by tooolbox** [superhx/golangdom#1]
Just curious:

You're probably aware of the existence of [GoQuery](https://github.com/PuerkitoBio/goquery) which is super-cool, but unfortunately lacks the ability to do stateful manipulations of the HTML/XML:

> Since the net/html parser returns nodes, and not a full-featured DOM tree, jQuery's stateful manipulation functions (like height(), css(), detach()) have been left off.

I'm doing a lot of on-disk processing of XHTML, using [Cheerio](https://github.com/cheeriojs/cheerio) for NodeJS.  For speed purposes I'd like to use Go instead, but there's no comparable tool.

Do you think golangdom could be used as the basis for something like GoQuery, but with the ability to do stateful manipulations of the DOM?

**Comment by superhx** [comment]
@tooolbox Sorry golangdom is just a project for me to practice golang. So golangdom currently don't support the function you mentioned and may not support in the future. Sorry for that.

**Comment by tooolbox** [comment]
No prob, just curious. :)
